### ISSUE TITLE
Delete the `src/shared/constants/WordClass` file

### ISSUE THREAD

**Issue by ijemmao** [nkowaokwu/igbo-api-admin#322]
## Background
There are two `WordClass` files that exist in the database — one in the `backend` directory and another in the top-level `shared` directory.

## Ideal Solution
Remove `src/shared/constants/WordClass` to only have `src/backend/shared/constants/WordClass`. Once the file has been deleted, you will need to update all the paths that pointed to the now deleted file to the existing `WordClass` file.

**Comment by ijemmao** [comment]
@giri-madhan done, thanks for taking this on!

**Comment by giri-madhan** [comment]
Welcome @ijemmao ! :)
