### ISSUE TITLE
 npm install -g firebase firebase-cli is depreacated 

### ISSUE THREAD

**Issue by Codehouze** [nkowaokwu/igbo-api-admin#327]
When you run the command "npm install -g firebase firebase-cli" in this project, you may encounter an issue with a deprecated package. This means that the package you are using is no longer maintained and may contain security vulnerabilities or bugs. It is recommended that you update the package to the latest version or find an alternative package that performs the same function. Failing to address the deprecated package may cause issues with the project's stability and security in the future.

I recommend using `npm install -g firebase-tools` instead.

To install `firebase-tools`, please run the following command:

 npm install -g firebase-tools

This will install the Firebase CLI tools and allow you to use the Firebase features in your project.

**Comment by ijemmao** [comment]
Closing this since it doesn't seem like a necessary change.
