### ISSUE TITLE
Convert the Personal Contributions section to become a grid.

### ISSUE THREAD

**Issue by ijemmao** [nkowaokwu/igbo-api-admin#341]
**Is your feature request related to a problem? Please describe.**
The Personal Contributions section on the Dashboard of the Igbo API Editor Platform is too tall. We should convert it to 6 column'd grid that includes all the stats that spans the entire viewport of the screen. If on a mobile device, the column should shrink down to 2 so that it reads better on smaller screens.

Use TailwindCSS grid syntax.

**Screenshot**
![Xnapper-2023-05-20-17 22 44](https://github.com/nkowaokwu/igbo-api-admin/assets/16169291/8e002f78-6645-4d2b-b997-e4724b8a211f)

**Comment by danieliheonu** [comment]
Could you please explain "We should convert it to 6 column'd grid that includes all the stats that spans the entire viewport of the screen.". Also how long should the personal contributions be

**Comment by ijemmao** [comment]
@danieliheonu i'm suggesting that we should use CSS grid to create a grid that has 6 columns, which means six items across. That way it will take up more horizontal space rather than the vertical space it's taking right now, shown in the screenshot.

this issue isn't requesting to change the size of each cell or the content within each cell. rather it's just focused on repositioning each cell so that it's taking up more horizontal space rather than vertical space. hope that helps with the explanation!

**Comment by danieliheonu** [comment]
@ijemmao I guess so. I'll get started and send in a PR for review

**Comment by kingdanie** [comment]
> @danieliheonu i'm suggesting that we should use CSS grid to create a grid that has 6 columns, which means six items across. That way it will take up more horizontal space rather than the vertical space it's taking right now, shown in the screenshot.
> 
> this issue isn't requesting to change the size of each cell or the content within each cell. rather it's just focused on repositioning each cell so that it's taking up more horizontal space rather than vertical space. hope that helps with the explanation!

Can you share a image or diagram for the proposed feature so it can be clearer? 
I have read your comment severally at I still dont get what you are saying

**Comment by ijemmao** [comment]
this ticket is no longer relevant! i'll close it
