### ISSUE TITLE
Convert `Box` into `Button` for `CrowdsourcingProgressManager`

### ISSUE THREAD

**Issue by ijemmao** [nkowaokwu/igbo-api-admin#354]
**Is your feature request related to a problem? Please describe.**
We want to make the Igbo API Editor Platform crowdsourcing homepage more accessible.

**Describe the solution you'd like**
Convert the `Box` component that renders each of our data collection options as a `Button` so the page is keyboard navigatable and screenreaders are more accurate.

Specifically, change the following usage: https://github.com/nkowaokwu/igbo-api-admin/blob/main/src/Core/Dashboard/components/CrowdsourcingProgressManager.tsx#L59-L82

**Comment by Chimise** [comment]
Hi, I would love to work on this issue
