### ISSUE TITLE
Expose an endpoint for the purpose of retrieving a user's referral code.

### ISSUE THREAD

**Issue by IfyNdu** [nkowaokwu/igbo-api-admin#455]
**Is your feature request related to a problem? Please describe.**
To enable users to access their individual referral codes, it is imperative to establish an API endpoint designed to facilitate the retrieval of a user's referral code.

**Describe the solution you'd like**

1. Expose an endpoint with the signature below
```
[GET] /user
```
2. It should communicate with `Mongodb's` `User` Collection as described here #450 and will return the entire user document containing a referral code.

**Additional context**
1. Software design [document](https://docs.google.com/document/d/1rP9LiRbWmVWxlGsr3PKxcP8_PL9Y7Siuy1MUfkGrLHM/edit?usp=sharing) for inspiration.

**Comment by IfyNdu** [comment]
@ijemmao 
Please assign this ticket to me. Thanks!

**Comment by ijemmao** [comment]
done! @IfyNdu
