### ISSUE TITLE
Expose an endpoint for the purpose of tracking referred users

### ISSUE THREAD

**Issue by IfyNdu** [nkowaokwu/igbo-api-admin#456]
**Is your feature request related to a problem? Please describe.**
In order to streamline the implementation of a referral code system, it is essential to establish a dedicated API endpoint tailored to monitor and allocate points to users who successfully refer other users.

**Describe the solution you'd like**
Expose an endpoint with the signature below
```
[POST] /referral?referral-code=<myawesomecode>
```
It should create a new referral with `Mongodb's` `User` Collection as described here #450.
1. Query the `User` collection described here #450 for the owner of the referral code
2. Use the response in the query above to create a `Referral` document also described here #450

**Additional context**
1. Software design [document](https://docs.google.com/document/d/1rP9LiRbWmVWxlGsr3PKxcP8_PL9Y7Siuy1MUfkGrLHM/edit?usp=sharing) for inspiration.

**Comment by IfyNdu** [comment]
@ijemmao
Please assign this ticket to me. Thanks!

**Comment by ijemmao** [comment]
done! @IfyNdu
