### ISSUE TITLE
Create a `Corpus` Model

### ISSUE THREAD

**Issue by ijemmao** [nkowaokwu/igbo-api-admin#58]
**Is your feature request related to a problem? Please describe.**
We want to be able to support long bodies of text along with audio. The `Corpus` model will enable us to do that.

**Describe the solution you'd like**
Create a new `Corpus` model that includes the following fields:
* body
* audio
* author

**Describe alternatives you've considered**
This is just the first version of the Corpus model

**Additional context**
N/A

**Comment by chialuka** [comment]
@ijemmao, is it reasonable to expect that some audio files may be larger than 16MB?

**Comment by ijemmao** [comment]
> @ijemmao, is it reasonable to expect that some audio files may be larger than 16MB?

It's a possibility, depending on how we plan on saving these audio files. Any thoughts on the way we wanna save this data?

**Comment by chialuka** [comment]
> Any thoughts on the way we wanna save this data?

It'd make the most sense to save to a cloud-based storage service like Cloudinary or Amazon S3. 

If we do want to save them to our database directly then we can use GridFS for files larger than 16MB
